# Generated by Django 5.2.6 on 2025-09-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='currency',
        ),
    ]
