# Generated by Django 5.2.6 on 2025-10-03 08:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_remove_course_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='presentations.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='If off, registrations auto-approve (or finalize if price=0).'),
        ),
        migrations.CreateModel(
            name='RegistrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_items', to='presentations.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presentations.registration')),
            ],
            options={
                'unique_together': {('registration', 'child_course')},
            },
        ),
    ]
