# Generated by Django 5.2.6 on 2025-10-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0005_coursesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesession',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='start_date',
        ),
    ]
