# Generated by Django 5.2.6 on 2025-10-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0006_rename_end_date_coursesession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
