# Generated by Django 5.2.6 on 2025-09-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='currency',
        ),
    ]
