# Generated by Django 5.2.6 on 2025-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_competition_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionfieldconfig',
            name='student_number',
            field=models.CharField(choices=[('REQ', 'Required'), ('OPT', 'Optional'), ('HID', 'Hidden')], default='OPT', max_length=3),
        ),
        migrations.AddField(
            model_name='competitionfieldconfig',
            name='university_name',
            field=models.CharField(choices=[('REQ', 'Required'), ('OPT', 'Optional'), ('HID', 'Hidden')], default='OPT', max_length=3),
        ),
    ]
