# Generated by Django 5.2.6 on 2025-10-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competitionfieldconfig_student_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='student_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teammember',
            name='university_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
