# Generated by Django 5.2.6 on 2025-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_teammember_student_number_teammember_university_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='signup_fee',
            new_name='signup_fee_aut',
        ),
        migrations.AddField(
            model_name='competition',
            name='signup_fee_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='is_aut',
            field=models.BooleanField(default=False),
        ),
    ]
