"""
Django settings for acm project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
ENV_FILE = BASE_DIR / ".env"
if ENV_FILE.exists():
    environ.Env.read_env(str(ENV_FILE))
else:
    print(f"[settings] WARNING: .env not found at {ENV_FILE}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-wci8i*h_0lxjng1cw!mi0taj4v)h2z=b03-a6s8pliv573m!bd')

# TODO: SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# TODO: Change this
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "drf_spectacular",
    "drf_spectacular_sidecar",
    'rest_framework',
    'django_filters',
    'accounts',
    'notification',
    'django_celery_results',
    'presentations',
    'competitions',
    'payment',
    'storages'
]

ZARINPAL_MERCHANT_ID = env("ZARINPAL_MERCHANT_ID", default="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
PAYMENT_CALLBACK_BASE = env("PAYMENT_CALLBACK_BASE", default="https://your-site.com/api/payment/callback/")
PAYMENT_FRONTEND_RETURN = env("PAYMENT_FRONTEND_RETURN", default="https://your-frontend.example/payresult")

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/2")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/3")
CELERY_TASK_ALWAYS_EAGER = False # set True for local dev if you want sync
CELERY_TASK_TIME_LIMIT = 30
CELERY_TASK_SOFT_TIME_LIMIT = 25


# Rate: e.g., Gmail ~100/h. You can tune down by minute if preferred.
NOTIF_EMAIL_RATE = env("NOTIF_EMAIL_RATE", default="30/m")
NOTIF_BULK_CHUNK_SIZE = env.int("NOTIF_BULK_CHUNK_SIZE", default=100)
NOTIF_BULK_RETRY_MAX = env.int("NOTIF_BULK_RETRY_MAX", default=5)
NOTIF_BULK_RETRY_BACKOFF = env.int("NOTIF_BULK_RETRY_BACKOFF", default=300)


EMAIL_PROVIDER = env("EMAIL_PROVIDER", default="smtp")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="your@gmail.com")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="app-password-or-secret")
EMAIL_USE_TLS = env.bool("EMAIL_USE_SSL", default=True)
EMAIL_DEFAULT_FROM = env("EMAIL_DEFAULT_FROM", default="ACM <no-reply@yourdomain>")


AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": SECRET_KEY,
    "ALGORITHM": "HS256",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "ACM API",
    "DESCRIPTION": "Authentication & user API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://127.0.0.1:6379/3"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "TIMEOUT": 60 * 60,
    }
}

OTP_SECRET = env("OTP_SECRET", default="change-me-super-secret")

REFRESH_TOKEN_COOKIE = {
    "key": "refresh_token",
    "httponly": True,
    "secure": True,
    "samesite": "Lax",
    "path": "/api/accounts/",
}

ROOT_URLCONF = 'acm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'acm.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ["MYSQL_DATABASE"],
        "USER": os.environ["MYSQL_USER"],
        "PASSWORD": os.environ["MYSQL_PASSWORD"],
        "HOST": os.getenv("MYSQL_HOST", "db"),
        "PORT": os.getenv("MYSQL_PORT", "3306"),
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

USE_CDN_STATIC = env.bool("USE_CDN_STATIC", default=not DEBUG)  # toggle via env

if USE_CDN_STATIC:
    STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")

    AWS_S3_REGION_NAME = "eu-west-1"

    # If using S3-compatible like Cloudflare R2 or MinIO, set the endpoint:
    #  R2 example: https://<ACCOUNT_ID>.r2.cloudflarestorage.com
    AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default=None)

    # Recommended: turn off querystring auth so URLs are clean/public
    AWS_QUERYSTRING_AUTH = False
    AWS_DEFAULT_ACL = None

    # Cache headers for long-lived static assets
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "public, max-age=31536000, immutable",
    }

    # Optional: serve via a CDN/custom domain (CNAME to your bucket or CDN)
    # Example (CloudFront / R2 custom domain): static.aut-icpc.ir
    AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN", default=None)

    # STATIC_URL should point to the bucket (or CDN). Prefer CUSTOM_DOMAIN if set.
    if AWS_S3_CUSTOM_DOMAIN:
        STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    elif AWS_S3_ENDPOINT_URL:
        # Virtual-hosted style (most providers). If path-style is required, set AWS_S3_ADDRESSING_STYLE="path" in env.
        STATIC_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"
    else:
        # Plain S3 without custom domain (uses AWS region endpoint)
        STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"

    # STATIC_ROOT is not used by django-storages, but keep it for dev
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
else:
    # Local/static during DEBUG or when USE_CDN_STATIC=0
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
