# Generated by Django 5.2.6 on 2025-09-25 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('COURSE', 'CourseRegistration'), ('COMPETITION', 'CompetitionTeamRequest')], max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='IRR', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('PG_INITIATE_ERROR', 'Gateway initiate error')], default='PENDING', max_length=24)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('card_pan', models.CharField(blank=True, max_length=32)),
                ('card_hash', models.CharField(blank=True, max_length=128)),
                ('zarinpal_code', models.CharField(blank=True, max_length=8)),
                ('zarinpal_message', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='payment_pay_user_id_94fc9f_idx'), models.Index(fields=['authority'], name='payment_pay_authori_8e0a58_idx'), models.Index(fields=['target_type', 'target_id', 'status'], name='payment_pay_target__6cd6d0_idx')],
            },
        ),
    ]
