# Generated by Django 5.2.6 on 2025-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='target_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
